### PR TITLE
Notification is back

### PR DESCRIPTION
**Pull request by iosdeveloper**

### CODE REVIEW

**Comment by a2** [comment]
I like your work, but the application could always just subscribe to the same notifications that MKiCloudSync does. Don't you agree?

**Comment by iosdeveloper** [comment]
Don't agree. If you have to update UI when pulled from iCloud, you don't know whether it has already merged into User Defaults.

**Comment by a2** [comment]
That makes sense. Okay.

**Comment by a2** [comment]
Fixed in commit 7bd8855bdd.

**Pull request closed without merging**
